name: Ma
options:
  bundleIdPrefix: com.birkelandit
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

targets:
  Ma:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: LifeOps
      - path: Shared
    settings:
      base:
        INFOPLIST_FILE: LifeOps/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.birkelandit.ma
        PRODUCT_NAME: Ma
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - target: MaWidget
        embed: true
    entitlements:
      path: LifeOps/LifeOps.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.birkelandit.ma

  MaWatch:
    type: application
    platform: watchOS
    deploymentTarget: "10.0"
    sources:
      - path: LifeOpsWatch
      - path: Shared/Models
      - path: Shared/Services
    settings:
      base:
        INFOPLIST_FILE: LifeOpsWatch/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.birkelandit.ma.watch
        PRODUCT_NAME: Ma
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        WK_COMPANION_APP_BUNDLE_IDENTIFIER: com.birkelandit.ma

  MaWidget:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: LifeOpsWidget
      - path: Shared/Models
    settings:
      base:
        INFOPLIST_FILE: LifeOpsWidget/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.birkelandit.ma.widget
        PRODUCT_NAME: MaWidget
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
    entitlements:
      path: LifeOpsWidget/LifeOpsWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.birkelandit.ma

schemes:
  Ma:
    build:
      targets:
        Ma: all
    run:
      config: Debug
    archive:
      config: Release

  MaWatch:
    build:
      targets:
        MaWatch: all
    run:
      config: Debug
    archive:
      config: Release
